server:
  port: 7940

keycloak:
  realm: <Your realm>
  auth-server-url: http://keycloak:8080/auth/
  ssl-required: none
  resource: <Your Client Name>
  credentials:
    secret: <Your Client Secret>
  use-resource-role-mappings: true
  bearer-only: true
  cors: true
  cors-max-age: 36000
  cors-allowed-methods: GET, HEAD, POST, PUT, DELETE, TRACE, OPTIONS, PATCH
  cors-allowed-headers: X-Requested-With, Content-Type, Authorization, Origin, Accept, Access-Control-Request-Method, Access-Control-Request-Headers

admin-client:
  domain: http://keycloak:8080
  grant_type: password
  admin: <Your username>
  password: <Your password>
  clientID: admin-cli
  realm: <Your realm>

aws:
  credentials:
    accessKeyId: <Secret>
    secretKeyId: <Secret>
    storage: <Secret>
    path: <Secret>

spring:
  zipkin:
    baseURL: http://zipkin-server:9411/
  sleuth:
    sampler:
      probability: 1
  data:
    mongodb:
      database: Product
      host: <Your host>
      port: <Your Port>

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://zuzul-eureka-server:8888/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"