server:
  port: 8990

spring:
  zipkin:
    baseURL: http://zipkin-server:9411/
  sleuth:
    sampler:
      probability: 1
    reactor:
      instrumentation-type: MANUAL
  cloud:
    gateway:
      routes: 
        - id: zuzul-authentication-service
          uri: lb://zuzul-authentication-service

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://zuzul-eureka-server:8888/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"