server:
  port: 8990

spring:
  zipkin:
    baseURL: http://zipkin-server:9411/
  sleuth:
    sampler:
      probability: 1
    reactor:
      instrumentation-type: MANUAL
  cloud:
    gateway:
      routes: 
        - id: zuzul-authentication-service
          uri: lb://zuzul-authentication-service
          predicates:
            - Path=/zuzul-authentication-service-api/**
          filters:
            - RewritePath=/zuzul-authentication-service-api, /zuzul-authentication-service
        - id: zuzul-product-public
          uri: lb://zuzul-product-public
          predicates:
            - Path=/zuzul-product-public-api/**
          filters:
            - RewritePath=/zuzul-product-public-api, /zuzul-product-public
        - id: zuzul-image-service
          uri: lb://zuzul-image-service
          predicates:
            - Path=/zuzul-image-service-api/**
          filters:
            - RewritePath=/zuzul-image-service-api, /zuzul-image-service


eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://zuzul-eureka-server:8888/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"